# judge0.conf
# This configures the internal databases for your local compiler

POSTGRES_USER=judge0
POSTGRES_PASSWORD=secure_postgres_password
POSTGRES_DB=judge0
POSTGRES_HOST=postgres
POSTGRES_PORT=5432

REDIS_PASSWORD=secure_redis_password
REDIS_HOST=redis
REDIS_PORT=6379

# Allow the worker to execute code
ALLOW_ENABLE_NETWORK=true